### ISSUE TITLE
Fullscreen button please

### ISSUE THREAD

**Issue by MadameMalady** [fafarunner/fafarunner#224]
I like your game so far, it's very cute!
happy a game for linux has touchscreen controls for my linux phone ^~^

anyways, I was wondering if it'd be hard to add a fullscreen button?

on my phone the game opens, but it has a large window-frame bar that displays the game name and won't go away, here's a pic of what I mean:
![Screenshot from 2024-09-19 20-53-14](https://github.com/user-attachments/assets/24c8bf72-df6e-4552-967a-36eab15e0b72)

**Comment by kjxbyz** [comment]
There is no "full screen switch" button on Linux, but there is one on macOS.

There are several solutions:

1. Add a floating button in the lower right corner of the page to switch to full screen.
2. Hide the native TitleBar and customize the TitleBar.
