### ISSUE TITLE
No colission on flag walls

### ISSUE THREAD

**Issue by SazanovGrigory** [fafarunner/fafarunner#269]
![Screenshot_20241226_103843_com chenyifaer fafarunner](https://github.com/user-attachments/assets/97a02e84-062a-47d2-ae67-fc8dcb52a8cf)

It is possible to go out of the map throw the flag walls. Collision error

![Screenshot_20241226_103850_com chenyifaer fafarunner](https://github.com/user-attachments/assets/2f0f2a13-9e44-46a5-9c72-7331386bf76d)

Tested on Android v1.0.4+369 and 1.0.5+370

**Comment by kjxbyz** [comment]
Thanks for your feedback, this is a known issue.

**Comment by kjxbyz** [comment]
1.0.6+371 has been released.

**Comment by johndh** [comment]
I'm still having this issue (or similar) on version 2.0.0 from F-droid.

![Image](https://github.com/user-attachments/assets/e76321fd-e861-40c3-bf5d-71a6c7623591)

**Comment by johndh** [comment]
> [@johndh](https://github.com/johndh) Can you please indicate the map location where the problem occurs?

It's the first time you encounter one of the fire breathing 150/150 monsters. I ran at it from an angle and slipped through the wall.

**Comment by johndh** [comment]
![Image](https://github.com/user-attachments/assets/549c6e9e-636b-47c9-876c-d09eb9a30a7c)

Just had it happen again, near the turn after the first spike trap. It wasn't a flag tile.

I wonder if it's related to the fireballs passing through enemies? Things in general just aren't colliding all the time?

![Image](https://github.com/user-attachments/assets/8660a8c9-6413-4751-9bfc-9615dbeabc39)
